### ISSUE TITLE
Trojan Horse Infection

### ISSUE THREAD

**Issue by GoogleCodeExporter** [gmoyle/autorip2mkv#3]
```
Your Setup.exe file is infected with the following Trojan Horse:

http://www.avgthreatlabs.com/virus-and-malware-information/info/trojanhorsegener
ic_c/?name=Trojan%20horse%20Generic11_c.NPE&utm_source=TDPU&utm_medium=RS&PRTYPE
=AVF

What steps will reproduce the problem?
1. Downloading the file( obviously )

What is the expected output? What do you see instead?
Threat Warning from AVG

What version of the product are you using? On what operating system?
v 2.3

```

Original issue reported on code.google.com by `soro...@gmail.com` on 4 Oct 2014 at 1:37

**Comment by gmoyle** [comment]
I don't believe this is a valid error, I did submit to them that it was a false positive. The most update version is 2.3. This project has had some serious neglect, mostly because the latest version was indeed working for me.  I also did not receive any notifications of these posting (hence the huge delay in response).

**Comment by gmoyle** [comment]
A new version installer 2.4 built on a completely new and clean PC.  I am not getting any virus reports on this one. I would love to hear if anyone else is still seeing it flagged as a virus.
